name: Handle Azure Pipeline Check Run

on:
  check_run:
    types: [completed]

jobs:
  process-check-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process Check Run Event
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Log the entire payload first for debugging
              console.log('Full context payload:');
              console.log(JSON.stringify(context.payload, null, 2));

              const checkRun = context.payload.check_run;
              if (!checkRun) {
                throw new Error('No check run data found in the payload');
              }

              // Log the entire checkRun object
              console.log('Full check run object:');
              console.log(JSON.stringify(checkRun, null, 2));

              console.log("Check run name:", checkRun.name);

              if (!checkRun.pull_requests || checkRun.pull_requests.length === 0) {
                console.log('No pull requests associated with this check run');
                return;
              }

              const pullRequest = checkRun.pull_requests[0];
              console.log('Processing check run for PR:', pullRequest.number);
              console.log('Check run details:', {
                name: checkRun.name,
                conclusion: checkRun.conclusion,
                status: checkRun.status,
                prNumber: pullRequest.number,
                headSha: pullRequest.head_sha
              });

              // Log annotations if they exist
              if (checkRun.output && checkRun.output.annotations) {
                console.log('Check run annotations:');
                console.log(JSON.stringify(checkRun.output.annotations, null, 2));

                // Log key properties of each annotation
                checkRun.output.annotations.forEach((annotation, index) => {
                  console.log(`Annotation ${index + 1}:`, {
                    message: annotation.message,
                    path: annotation.path,
                    level: annotation.annotation_level,
                    start_line: annotation.start_line,
                    end_line: annotation.end_line
                  });
                });
              } else {
                console.log('No annotations found in check run');
              }
            } catch (error) {
              console.error('Error processing check run:', error);
              throw error;
            }
