name: Handle Azure Pipeline Check Run

on:
  check_run:
    types: [completed]

jobs:
  process-check-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process Check Run Event
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Log the entire payload first for debugging
              console.log('Full context payload:');
              console.log(JSON.stringify(context.payload, null, 2));

              const checkRun = context.payload.check_run;
              if (!checkRun) {
                throw new Error('No check run data found in the payload');
              }

              // Log the entire checkRun object
              console.log('Full check run object:');
              console.log(JSON.stringify(checkRun, null, 2));

              console.log("Check run name:", checkRun.name);

              if (!checkRun.pull_requests || checkRun.pull_requests.length === 0) {
                console.log('No pull requests associated with this check run');
                return;
              }

              const pullRequest = checkRun.pull_requests[0];
              console.log('Processing check run for PR:', pullRequest.number);
              console.log('Check run details:', {
                name: checkRun.name,
                conclusion: checkRun.conclusion,
                status: checkRun.status,
                prNumber: pullRequest.number,
                headSha: pullRequest.head_sha
              });

              // Check if there are annotations and fetch them
              if (checkRun.output && checkRun.output.annotations_count > 0) {
                console.log(`Found ${checkRun.output.annotations_count} annotations`);

                // Parse the annotations URL to get required parameters
                const annotationsUrl = new URL(checkRun.output.annotations_url);
                const pathParts = annotationsUrl.pathname.split('/');
                const checkRunId = pathParts[pathParts.length - 2];

                // Fetch annotations using octokit
                const annotations = await github.rest.checks.listAnnotations({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  check_run_id: parseInt(checkRunId)
                });

                console.log('Fetched annotations:');
                console.log(JSON.stringify(annotations.data, null, 2));

                // Log key properties of each annotation
                annotations.data.forEach((annotation, index) => {
                  console.log(`Annotation ${index + 1}:`, {
                    message: annotation.message,
                    path: annotation.path,
                    level: annotation.annotation_level,
                    start_line: annotation.start_line,
                    end_line: annotation.end_line
                  });
                });
              } else {
                console.log('No annotations found in check run');
              }
            } catch (error) {
              console.error('Error processing check run:', error);
              throw error;
            }
