name: Handle Azure Pipeline Check Run

on:
  check_run:
    types: [completed]

jobs:
  process-check-run:
    # Only run this job if:
    # 1. The check run is from Azure Pipelines
    # 2. The check is associated with a pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process Check Run Event
        uses: actions/github-script@v7
        with:
          script: |
            console.log("event.check_run.name: ", github.event.check_run.name);
            console.log("event.check_run.pull_requests: ", github.event.check_run.pull_requests);
            if (github.event.check_run.pull_requests != null) {
              console.log("event.check_run.pull_requests[0]: ", github.event.check_run.pull_requests[0]);
            }
            // Dump the entire payload with proper formatting
            console.log('Full check run payload:');
            console.log(JSON.stringify(context.payload, null, 2));
            
            // Keep existing logging
            const checkRun = context.payload.check_run;
            const pullRequest = checkRun.pull_requests[0];
            
            console.log('Processing check run for PR:', pullRequest.number);
            console.log('Check run details:', {
              name: checkRun.name,
              conclusion: checkRun.conclusion,
              status: checkRun.status,
              prNumber: pullRequest.number,
              headSha: pullRequest.head_sha
            });
